name: 'sfta'
services:
  app:
    container_name: app
    hostname: app
    volumes:
      - ${UPLOADS_DIR:?error}:/var/www/uploads:rw
    env_file:
      - .env
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:stable
    ports:
      - ${HTTP_HOST_PORT:?error}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${UPLOADS_DIR:?error}:/var/www/uploads:ro
    env_file:
      - .env
